---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-manage-v2
  labels:
    app: api_manage-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api_manage_app_v2
  template:
    metadata:
      labels:
        app: api_manage_app_v2
    spec:
      containers:
      - name: api-manage-v2
        image: api_manage:v2
        ports:
        - containerPort: 8181

---
apiVersion: v1
kind: Service
metadata:
  name: api-manage-service-v2
spec:
  type: NodePort
  selector:
    app: api_manage_app_v2
  ports:
      # 默认情况下，为了方便起见，`targetPort` 被设置为与 `port` 字段相同的值。
    - port: 8181
      protocol: TCP
      targetPort: 8181
      # 可选字段
      # 默认情况下，为了方便起见，Kubernetes 控制平面会从某个范围内分配一个端口号（默认：30000-32767）
      nodePort: 30001
